# Generated by Django 4.2 on 2023-04-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("Captain", "Captain"),
                    ("Yacht Admin", "Yacht Admin"),
                    ("Agent", "Agent"),
                    ("Manager", "Manager"),
                ],
                default="Captain",
                max_length=50,
            ),
        ),
    ]
