# Generated by Django 4.2 on 2023-04-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vessels", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vessel",
            name="beam",
        ),
        migrations.RemoveField(
            model_name="vessel",
            name="draft",
        ),
        migrations.RemoveField(
            model_name="vessel",
            name="length",
        ),
        migrations.AddField(
            model_name="vessel",
            name="beam_meters",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vessel",
            name="draft_meters",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vessel",
            name="length_meters",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vessel",
            name="ntvrp_exp",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vessel",
            name="cruising_permit_exp",
            field=models.DateField(blank=True, null=True),
        ),
    ]
