# Generated by Django 4.2 on 2023-04-25 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vessels", "0003_rename_ism_status_vessel_is_ism_vessel_notes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vessel",
            old_name="name_vessle",
            new_name="vessel_name",
        ),
    ]
